plugins {
    id 'java'
    id 'org.springframework.boot' version '2.2.6.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
}

group = 'kr.co.ultari'
version = '0.0.1-SNAPSHOT'
description = 'ultari ai chatbot'
sourceCompatibility = '1.8'

bootJar {
    enabled = true
    archiveBaseName = 'chatbot'
    archiveVersion = '1.0.0.RELEASE'
}

repositories {
	mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
    testCompileOnly 'org.projectlombok:lombok:1.18.32'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.json:json:20231013'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    implementation fileTree (dir: 'lib', include:['**/*.jar'])
}

tasks.named('test') {
	useJUnitPlatform()
}
