plugins {
    id 'java'
    id 'org.springframework.boot' version '2.2.6.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
}

group = 'kr.co.ultari'
version = '0.0.1-SNAPSHOT'
description = 'ultari ai chatbot'
sourceCompatibility = '1.8'

bootJar {
    enabled = true
    archiveBaseName = 'chatbot'
    archiveVersion = '1.0.0.RELEASE'
}

repositories {
	mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
    testCompileOnly 'org.projectlombok:lombok:1.18.32'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'kr.dogfoot:hwplib:1.0.1'
    implementation 'kr.dogfoot:hwpxlib:1.0.8'
    implementation 'org.apache.pdfbox:pdfbox:2.0.27'
    implementation 'org.apache.pdfbox:pdfbox-tools:2.0.27'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    implementation 'org.apache.logging.log4j:log4j-api:2.17.2'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.2'
    implementation 'org.json:json:20231013'
    runtimeOnly 'mysql:mysql-connector-java'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    implementation fileTree (dir: 'lib', include:['**/*.jar'])
}

tasks.named('test') {
	useJUnitPlatform()
}
