spring.application.name=chatbot
spring.profiles.active=main
server.port=8888
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.config=classpath:logback-chatbot.xml

#https://pok-chromospheric-rumblingly.ngrok-free.dev/v1/chat/completions
ultari.ai.url=http://10.0.0.91:11434/v1/chat/completions
#QuantTrio/Qwen3-30B-A3B-Thinking-2507-AWQ
ultari.ai.model=qwen2.5:7b

ultari.ai-gateway.url=http://192.168.0.27:8000/message

ultari.ai.temp.path=D:\\projects\\chatbot\\tmp

ultari.ai.summary-size=8