spring.application.name=chatbot
spring.profiles.active=relay
server.port=8888
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.config=classpath:logback-chatbot.xml

#active=chat ??
#https://pok-chromospheric-rumblingly.ngrok-free.dev/v1/chat/completions
ultari.ai.url=http://localhost:11434/api/generate
#QuantTrio/Qwen3-30B-A3B-Thinking-2507-AWQ
ultari.ai.model=qwen2.5:7b
ultari.ai.temp.path=D:\\projects\\chatbot\\tmp
ultari.ai.summary-size=8

#active=relay ??
ultari.ai-gateway.chat-private-url=http://10.0.0.111:8000/message/private
ultari.ai-gateway.chat-url=http://10.0.0.111:8000/message/open
ultari.ai-gateway.upload-url=http://10.0.0.111:8000/upload
ultari.ai-gateway.files-url=http://10.0.0.111:8000/files
ultari.ai-gateway.template-url=http://10.0.0.111:8000/documents/generate-hwpx
ultari.ai-gateway.call-summary-url=http://10.0.0.111:8000/call-summary
ultari.ai-gateway.doc-summary-url=http://10.0.0.111:8000/message/document-summary
ultari.ai-gateway.dialog-summary-url=http://10.0.0.111:8000/convert/dialogue-summary
ultari.ai-gateway.download-url=http://10.0.0.111:8000/documents/download

ultari.interface-summary.url=http://10.0.0.91:8888/chatbot/summary


#DB ??
spring.datasource.url=jdbc:mysql://10.0.0.91:3306/chatbot?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=msger
spring.datasource.password=msger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.max-lifetime=1800000